//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class AppUserInfo
{
	String pub0, pub1, pub2, pub3, pub4, pub5, pub6, pub7, pub8, pub9;
	public String Pub0 {
		get {
			return pub0;
		}
	}
	public String Pub1 {
		get {
			return pub1;
		}
	}
	public String Pub2 {
		get {
			return pub2;
		}
	}
	public String Pub3 {
		get {
			return pub3;
		}
	}
	public String Pub4 {
		get {
			return pub4;
		}
	}
	public String Pub5 {
		get {
			return pub5;
		}
	}
	public String Pub6 {
		get {
			return pub6;
		}
	}
	public String Pub7 {
		get {
			return pub7;
		}
	}
	public String Pub8 {
		get {
			return pub8;
		}
	}
	public String Pub9 {
		get {
			return pub9;
		}
	}

	
	public AppUserInfo (String pub0, String pub1,
	                    String pub2, String pub3,
	                    String pub4, String pub5,
	                    String pub6, String pub7,
	                    String pub8, String pub9) {
		this.pub0 = pub0;
		this.pub1 = pub1;
		this.pub2 = pub2;
		this.pub3 = pub3;
		this.pub4 = pub4;
		this.pub5 = pub5;
		this.pub6 = pub6;
		this.pub7 = pub7;
		this.pub8 = pub8;
		this.pub9 = pub9;
	}
}
